---
name: {{ cookiecutter.project_slug }}-workflow-publish-to-galaxy

# This workflow is configured by values found in the .github/config/workflows/workflow-publish-to-galaxy.json file.
# It's encouraged to explore the configuration before customizing this file.
# This will allow you to upgrade to future versions of this template without complications.

# For further details please consult the documentation here:
# https://github.com/niall-byrne/ansible-workbench

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      TAG:
        description: 'Tag to Deploy'
        required: true
        default: ''

#  secrets:
#    SLACK_WEBHOOK:
#      description: "Optional, enables Slack notifications."
#      required: false


jobs:

  configuration:

    runs-on: ubuntu-latest
    outputs:
      configuration: {% raw %}${{ steps.configuration.outputs.value }}{% endraw %}
      publish-to-galaxy: {% raw %}${{ steps.publish-to-galaxy.outputs.publish-to-galaxy }}{% endraw %}

    steps:
      - name: Create Configuration -- Checkout Repository
        uses: {{ cookiecutter._GITHUB_ACTION_CHECKOUT }}

      - name: Create Configuration -- Set Publish to Galaxy as Output
        id: publish-to-galaxy
        run: |
          [[ -n "${API_KEY}" ]] && PUBLISH_TO_GALAXY="true" || PUBLISH_TO_GALAXY="false"
          echo "publish-to-galaxy=${PUBLISH_TO_GALAXY}" >> "${GITHUB_OUTPUT}"
        env:
          API_KEY: {% raw %}${{ secrets.GALAXY_API_KEY }}{% endraw %}

      - name: Create Configuration -- Validate the 'workflow-publish-to-galaxy.json' File
        run: |
          python -m json.tool "./.github/config/workflows/workflow-publish-to-galaxy.json" >> /dev/null

      - name: Create Configuration -- Set the 'workflow-publish-to-galaxy.json' Configuration File as Output
        id: configuration
        run: |
          source "./.github/scripts/workflow-set-value.sh" cat "./.github/config/workflows/workflow-publish-to-galaxy.json"

  publish_to_galaxy:
    needs: [configuration]
    if: needs.configuration.outputs.publish-to-galaxy == 'true'
    uses: ./.github/workflows/.job-99-import-role.yml
    with:
      PYTHON_VERSION: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_python_version }}{% endraw %}
      WORKFLOW_DISPATCH: {% raw %}${{ github.event_name == 'workflow_dispatch' }}{% endraw %}
      VERBOSITY: {% raw %}${{ fromJSON(needs.configuration.outputs.configuration).ci_verbose_notifications }}{% endraw %}
    secrets: inherit
