---
- name: Converge
  hosts: all
  connection: local
  vars:
    test: true
  tasks:
    - name: "Include {{ cookiecutter.galaxy_namespace_slug }}.{{ cookiecutter.galaxy_role_slug }}"
      ansible.builtin.include_role:
        name: "{{ cookiecutter.galaxy_namespace_slug }}.{{ cookiecutter.galaxy_role_slug }}"
