---
version: 2
updates:
  - package-ecosystem: "pip"
    target-branch: "{{ cookiecutter._BRANCH_NAME_BASE }}"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
    reviewers:
      - "{{ cookiecutter.github_handle }}"
