---
- name: Converge
  hosts: all
  connection: local

  tasks:
    - name: Load Scenario Variables
      ansible.builtin.include_vars: vars/main.yml
    - name: "Include {{ cookiecutter.galaxy_namespace_slug }}.{{ cookiecutter.galaxy_role_slug }}"
      ansible.builtin.include_role:
        name: "{{ cookiecutter.galaxy_namespace_slug }}.{{ cookiecutter.galaxy_role_slug }}"
