---
name: ansible-workbench-job-molecule

on:
  workflow_call:
    inputs:
      CONFIGURATION:
        description: "The 'cookiecutter.json' file as a configuration object."
        required: true
        type: string
    secrets:
      SLACK_WEBHOOK:
        description: "Optional, enables Slack notifications."
        required: false

env:
  ANSIBLE_WORKBENCH_SKIP_POETRY: 0
  ANSIBLE_WORKBENCH_SKIP_PRECOMMIT: 0

jobs:

  run_molecule_lint:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ${{ fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_PYTHON_VERSIONS }}
      max-parallel: ${{ fromJSON(inputs.CONFIGURATION)._GITHUB_CI_DEFAULT_CONCURRENCY }}

    steps:
      - name: Molecule Lint Test -- Checkout Repository
        uses: actions/checkout@v3
        with:
          path: 'template'

      - name: Molecule Lint Test -- Setup Environment
        run: |
          source "./template/.github/scripts/workflow-setup-environment.sh"
          source "./template/{{cookiecutter.project_slug}}/.github/scripts/setup.sh"
        env:
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Molecule Lint Test -- Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Molecule Lint Test -- Install Template Requirements
        run: |
          source "./template/.github/scripts/task-template-requirements.sh"

      - name: Molecule Lint Test -- Initialize Cache Locations
        run: |
          mkdir -p ~/.cache/pypoetry/virtualenvs
          source "./template/{{cookiecutter.project_slug}}/.github/scripts/ansible_cache.sh"  \
            "$(pwd)/ansible_cache"                                                          \
            ~/.cache

      - name: Molecule Lint Test -- Mount Ansible Cache
        uses: actions/cache@v3
        with:
          key: ansible-${{ hashFiles('./template/{{cookiecutter.project_slug}}/requirements.yml') }}-${{ env.CACHE_TTL }}
          path: ansible_cache

      - name: Molecule Lint Test -- Mount Poetry Cache
        uses: actions/cache@v3
        with:
          key: poetry-${{ hashFiles('./template/{{cookiecutter.project_slug}}/pyproject.toml') }}-${{ runner.os }}-${{ env.CACHE_TTL }}
          path: ~/.cache/pypoetry/virtualenvs

      - name: Molecule Lint Test -- Render Template
        run: |
          source "./template/.github/scripts/task-render-template.sh"

      - name: Molecule Lint Test -- Lint Rendered Template With Default Scenario
        run: |
          cd "${TEMPLATED_NAME}"
          poetry run molecule lint

      - name: Molecule Lint Test -- Report Job Status on Success
        if: fromJSON(inputs.CONFIGURATION)._GITHUB_CI_VERBOSE_NOTIFICATIONS == true
        run: |
          "./template/{{cookiecutter.project_slug}}/.github/scripts/notifications.sh" "${NOTIFICATION}" ":white_check_mark: molecule linting checks succeeded!"

      - name: Molecule Lint Test -- Report Job Status on Failure
        if: failure()
        run: |
          "./template/{{cookiecutter.project_slug}}/.github/scripts/notifications.sh" "${NOTIFICATION}" ":x: molecule linting checks failed!"
